### ISSUE TITLE
Document purpose and status of this fork

### ISSUE THREAD

**Issue by novoid** [akirak/org-edna#1]
Hi,

I was using your repo for the last 8 months or so when I began to test org-edna for my setup. I can't remember why I chose it in the first place. Maybe it seemed more actively maintained than the original project.

Meanwhile, I've contributed ideas to the original org-edna which got published this week. Finding out that I'm not using the original version, I now want to know if I should change to the original repo instead.

Could you please add a README where you elaborate on the differences between this repo and the original, your plans, your idea on how fast you might want to add new commits to the original project to your project and so forth.

Thank you very much!

PS: I was in Fukuoka last summer. Damn, we could have met when I'd have started earlier with your repo ;-) Greetings from Graz/Austria!

**Comment by akirak** [comment]
Hi @novoid,

> Could you please add a README where you elaborate on the differences between this repo and the original, your plans, your idea on how fast you might want to add new commits to the original project to your project and so forth.

The differences between this fork and the original version are:

- Added some fancy features to the `org-edna-edit` buffer.
- Also added `org-edna-avy.el`.

The original version is maintained in bzr, and I didn't know how to contribute to it, so I created a repository instead here on GitHub.

> I can't remember why I chose it in the first place. Maybe it seemed more actively maintained than the original project.

Perhaps it was because I created a thread on reddit. I'm not using org-edna now, and I'm not willing to maintain this repository any more. Meanwhile, Karl Voit has recently published [a blog post](https://karl-voit.at/2020/08/14/project-mgt-draft/) on org-edna, so it would be great for you to contribute to the original one. I think I have to archive this repository to avoid confusion. Thank you for your advice.

> PS: I was in Fukuoka last summer. Damn, we could have met when I'd have started earlier with your repo ;-) Greetings from Graz/Austria!

Thanks, I seldom meet people offline, but it would have been great to see you. I resettled in this city last year. I have never been to Europe, but I wish to visit your country someday.

**Comment by novoid** [comment]
> Meanwhile, Karl Voit has recently published [a blog post](https://karl-voit.at/2020/08/14/project-mgt-draft/) on org-edna

I am Karl Voit ;-)

Thanks for the clarification. Love to see your contributions as an input to the original version.

If you're ever in Austria, drop me a line.

**Comment by akirak** [comment]
> I am Karl Voit ;-)

Sorry for my confusion, but I like the blog. It's great to talk to you.
